# Generated by Django 5.0.6 on 2024-05-15 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networknode",
            options={"verbose_name": "Узел сети", "verbose_name_plural": "Узлы сети"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active_employee",
            field=models.BooleanField(default=False, verbose_name="Активный сотрудник"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="city",
            field=models.CharField(max_length=255, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="country",
            field=models.CharField(max_length=255, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Задолженность"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="house_number",
            field=models.CharField(max_length=10, verbose_name="Номер дома"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="product_model",
            field=models.CharField(max_length=255, verbose_name="Модель продукта"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="product_name",
            field=models.CharField(max_length=255, verbose_name="Название продукта"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="product_release_date",
            field=models.DateField(verbose_name="Дата выхода продукта на рынок"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="street",
            field=models.CharField(max_length=255, verbose_name="Улица"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="network.networknode",
                verbose_name="Поставщик",
            ),
        ),
    ]
