# Generated by Django 5.0.6 on 2024-05-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_networknode_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Задолженность",
            ),
        ),
    ]
